baseURL = "http://hangaroundtheweb.com/"
languageCode = "en-us"
title = "hangaroundtheweb"
theme = "ananke"
show_reading_time = "true"
googleAnalytics = "UA-19638992-3"
disqusShortname = "hangaroundtheweb"
[params]
  favicon = ""
  site_logo = ""
  twitter = "https://twitter.com/rajasegar_c"
  github = "https://github.com/rajasegar"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  commentoEnable = true
